app/videostream/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError,PasswordField, HiddenField, IntegerField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms.ext.sqlalchemy.fields import QuerySelectField

class FuncionForm(FlaskForm):
    inicio = StringField("Hora de Inicio",validators=[DataRequired()])
    fin = StringField("Hora de Fin", validators=[DataRequired()])
    submit= SubmitField('Agregar')

app/videostream/__init__.py
from flask import Blueprint

videostream = Blueprint('videostream',__name__)

from . import views

app/videostream/views.py
from flask import render_template, abort, Response, Flask, redirect, url_for, flash, request, current_app,jsonify
from flask_login import login_required, current_user
from . import videostream
from ..models import Funciones, Eventos, Configuraciones, Usuario, UsuarioNotificacion
from .forms import FuncionForm
from .. import db, mail
import time, json
import requests
from requests.auth import HTTPBasicAuth

def chequeo_admin():
    if not current_user.is_admin:
        abort(403)


@videostream.route('/videostream/stream/<string:id_cam>', methods=['GET'])
@login_required
def stream(id_cam):

    #link_ngrok = Configuraciones.query.filter_by(nombre='ngrok').first().config + '/videostream/' + id_cam
    urlcam = Configuraciones.query.filter_by(descripcion=id_cam).first().config

    return render_template('videostream/stream.html', link=urlcam, title=id_cam.upper())


@videostream.route('/videostream/funciones')
@login_required
def funciones():
    chequeo_admin()
    funcion = Funciones.query.get_or_404(1)
    form = FuncionForm()
    form.inicio = funcion.inicio
    form.fin = funcion.fin
    return render_template("videostream/funcion.html", funcion=funcion, form=form, title="Administrar Tarea")


@videostream.route('/iniciarfin/<string:inicia>')
@login_required
def iniciar_fin(inicia):
    hecho = True
    
    while hecho:
        try:
            chequeo_admin()
            funcion = Funciones.query.get_or_404(1)
            link_ngrok = Configuraciones.query.filter_by(nombre='ngrok').first().config
            usu=Configuraciones.query.filter_by(nombre='user-ngrok').first().config
            contra=Configuraciones.query.filter_by(nombre='pass-ngrok').first().config
            
            result = requests.post(link_ngrok + '/reconocimiento/' + inicia).text#,auth=HTTPBasicAuth(usu,contra))
            
            hecho=False
           
            flash(json.loads(result)['msg'])
            return redirect(url_for('videostream.funciones'))

        except Exception as e:
            #mensaje de error
            abort(500)




@videostream.route('/periodo', methods=['POST'])
@login_required
def periodo():
    hecho = True

    while hecho:
        try:
            chequeo_admin()
            form = request.form
            funcion = Funciones.query.get_or_404(1)
            funcion.inicio = form['inicio']
            funcion.fin = form['fin']
            db.session.commit()
            hecho=False
            msg = 'Se modifico exitosamente los periodos de Monitoreo!!!'
            flash(msg)
            return redirect(url_for('videostream.funciones'))

        except Exception as e:
            abort(500)


@videostream.route('/listaeventos')
def lista_eventos():

    #chequeo_admin()
    #cargo la lista de eventos
    eventos= Eventos.query.all()

    return render_template('videostream/eventos.html',eventos=eventos, title='Listado de Eventos')



@videostream.route('/videostream/get_imagen', methods=['POST'])
def get_imagen():
    paths = json.loads(request.data)["path"]

    linkngrok= Configuraciones.query.filter_by(nombre='ngrok').first().config
    response = requests.get(linkngrok + "/evento", data=json.dumps(paths),headers = {'content-type': 'application/json'})

    return Response(response)

app/templates/videostream/eventos.html
{% import "bootstrap/utils.html" as utils %}
{% extends 'base.html' %}
{% block blockname %}
Lista de Eventos
{% endblock blockname %}

{% block body %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css" />
<style>
.page-link{
    background-color: #2c3e50 !important;

}

.page-link:hover{
    background-color: #37536e !important;
}
.page-item.disabled .page-link{
    background-color: #2c3e50 !important;
}
.page-item.active .page-link{
    background-color: #385673 !important;

}

</style>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>
<div class="container text-center">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br />
                {{ utils.flashed_messages() }}
                <br />
                <h1 style="text-align:center;">Listado de Eventos</h1>
                {% set count = {'value': 1} %}
                {% if eventos %}
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered" >
                        <thead>
                            <tr class="text-center">
                                <th width="20%"> # </th>
                                <th width="20%"> Evento </th>
                                <th width="20%"> Hora </th>
                                <th width="15%"> Ver Imagen</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for evento in eventos %}
                            <tr>

                                <td>
                                    {{count.value}}
                                </td>

                                <td>
                                    {{ evento.evento }}
                                </td>
                                <td>
                                    {{ evento.hora }}
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary" data-toggle="modal"
                                        onclick="cargaimg('{{ evento.path }}','{{ evento.evento }}','{{ evento.hora }}')"
                                        data-target="#myModal">
                                        Ver
                                    </button>
                                </td>

                            </tr>
                              {% if count.update({'value': (count.value + 1)}) %} {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                {% else %}
                <hr class="intro-divider">
                <div style="text-align: center">
                    <h3> No hay Eventos!!! </h3>

                </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header" style="justify-content: center;">
                <h4 class="modal-title "  id="title"></h4>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <img src="{{ url_for('static', filename = 'img/loading.gif') }}" alt="" id="CaptchaImg" style="width:100%">
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>
<script>
    function cargaimg(path, cam, hora) {
        $("#title").html(cam + " - " + hora);
        $.ajax({
            url: '/videostream/get_imagen',
            data: JSON.stringify({ path: path}),
            contentType: 'application/json;charset=UTF-8',
            type: 'POST',
            success: function (response) {
                src = 'data:image/png;base64,' + response;

                $("#CaptchaImg").attr("src", src);
                $("#title").html(cam + " - " + hora);
            },


        });

    };
    $(document).ready(function () {

        var oTable=$('table').DataTable({
                language: {
        "decimal": "",
        "emptyTable": "No hay información",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ Entradas",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
        }
         }
            });
            
            $('#myModal').on('hidden.bs.modal', function (e) {
                $("#CaptchaImg").attr("src", "../../static/img/loading.gif");

            });
            
    })
</script>
{% endblock %}

app/templates/videostream/funcion.html
{% import "bootstrap/utils.html" as utils %}

{% extends 'base.html' %}

{% block title %}Administrar Funcion de Reconocimiento{% endblock title %}
{% block body %}

<div class="jumbotron jumbotron-fluid">

    {{ utils.flashed_messages() }}

    <div class="container">
        <h3>Administrar Tarea de Reconocimiento de las Camaras de Vigilancia</h3>
        <hr class="my-1">
        <p>Reconocimiento de Personas y Autos de los videos captados por las camaras, si se detecta alguno de estos objetos se
            enviara una notificacion a los usuarios segun haya sido configurados las notificaciones.</p>
        <h4 class="color: #aec251"><b><u>Estado de la Tarea</u></b></h4>
        <div class="w-100"></div><br>
        <div class="row text-center">

        {% if funcion.corriendo>0 %}
            <div class="col-6" style="border-right: 1px solid #c6c7c7 !important">
                <h3 style="color: #2c3e50"><b>Corriendo</b></h3>
            </div>
            <div class="col-6">
                <a href="{{ url_for('videostream.iniciar_fin',inicia=False) }}" class="btn btn-lg btn-danger" style="font-weight: bold;">Detener</a>
            </div>
        {% else %}
            <div class="col-6" style="border-right: 1px solid #c6c7c7 !important">
                <h3 style="color: #2c3e50"><b>Detenido</b></h3>
            </div>
            <div class="col-6">
                <a href="{{ url_for('videostream.iniciar_fin',inicia=True) }}" class=" btn btn-lg btn-success" style="font-weight: bold;">Iniciar</a>
            </div>
        {% endif %}
        <hr class="w-100">
        </div>


    </div>
    <div class="container">


            <h3>Hora de Inicio y Fin Del Periodo de Ejecucion del Reconocimiento de Objetos</h3>
            <hr class="my-2">
            <div class="offset-sm-1">
                <form action="{{ url_for('videostream.periodo') }}" method="post">
                    {{ form.csrf_token }}
                      {% if funcion.corriendo>0 %}
                        <div class="form-group">
                            <h4 class="color: #aec251"><b>Inicio:</b></h4>
                            <div class="col col-6">
                                <input type="number" name="inicio" value="{{ form.inicio }}" class="form-control" disabled>
                            </div>
                         </div>
                        <div class="form-group">
                            <h4 class="color: #aec251"><b>Fin:</b></h4>
                            <div class="col col-6">
                                <input type="number" name="fin" value="{{ form.fin }}" class="form-control" disabled>
                            </div>
                        </div>
                        <input type="button" id="block" value="Guardar" class="btn btn-primary btn-lg"  data-toggle="tooltip" data-placement="top" title="No se puede editar el periodo, por que el RECONOCIMIENTO esta en ejecucion. Detenga el mismo para la edicion."/>
                        <script>
                            $(document).ready(function(){
                                $("#block").tooltip('enable');
                            });
                        </script>
                      {% else %}
                         <div class="form-group">
                            <h4 class="color: #aec251"><b>Inicio:</b></h4>
                            <div class="col col-6">
                                <input type="number" name="inicio" value="{{ form.inicio }}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <h4 class="color: #aec251"><b>Fin:</b></h4>
                            <div class="col col-6">
                                <input type="number" name="fin" value="{{ form.fin }}" class="form-control">
                            </div>
                        </div>
                        <input name="submit" type="submit" value="Guardar" class="btn btn-primary btn-lg" />
                      {% endif %}

                </form>

            </div>


    </div>
</div>

{% endblock %}

app/templates/videostream/stream.html
{% extends 'base.html' %}

{% block body %}

<div class="jumbotron text-center">
    <h1 style="font-size: 4vh;">Camaras de Vigilacia: {{ title }}</h1>
    <!-- <p class="lead">Jumbo helper text</p> -->
    <hr class="my-2">
    <!-- <p>More info</p> -->
    <br>
    <div class="row justify-content-center align-items-center minh-100">
        <div class="col-sm-6  mb-3">
           
            <img src="{{ link }}" class="img-fluid shadow-lg" alt="" id="video" >

        </div>

    </div>
    
</div>
<script>    

    $(document).ready(function(){
       
        $("#video").on("error",function () {
            $(this).attr("src","../../static/img/404.gif")
      });
    } );
    

</script>
{% endblock  %}